package com.sekusarisu.yanami.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * 主题颜色方案枚举
 *
 * 每种预设颜色包含亮色和暗色两套 MD3 ColorScheme。 DYNAMIC 表示使用系统壁纸动态取色（仅 Android 12+）。
 */
enum class ThemeColor(
        val key: String,
        val seedColor: Color,
        val lightScheme: ColorScheme?,
        val darkScheme: ColorScheme?
) {
    /** 动态壁纸取色（Android 12+） */
    DYNAMIC(key = "dynamic", seedColor = Color(0xFF006B5E), lightScheme = null, darkScheme = null),

    /** 青绿 — 默认 */
    TEAL(
            key = "teal",
            seedColor = Color(0xFF006B5E),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF006B5E),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFF7AF7E0),
                            onPrimaryContainer = Color(0xFF00201B),
                            secondary = Color(0xFF4A635D),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFCDE8E0),
                            onSecondaryContainer = Color(0xFF06201B),
                            tertiary = Color(0xFF436278),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFC8E6FF),
                            onTertiaryContainer = Color(0xFF001E30),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFAFDFA),
                            onBackground = Color(0xFF191C1B),
                            surface = Color(0xFFFAFDFA),
                            onSurface = Color(0xFF191C1B),
                            surfaceVariant = Color(0xFFDAE5E0),
                            onSurfaceVariant = Color(0xFF3F4945),
                            outline = Color(0xFF6F7975),
                            outlineVariant = Color(0xFFBEC9C4),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFF5CDAC4),
                            onPrimary = Color(0xFF003830),
                            primaryContainer = Color(0xFF005046),
                            onPrimaryContainer = Color(0xFF7AF7E0),
                            secondary = Color(0xFFB1CCC4),
                            onSecondary = Color(0xFF1D352F),
                            secondaryContainer = Color(0xFF334B46),
                            onSecondaryContainer = Color(0xFFCDE8E0),
                            tertiary = Color(0xFFAACBE3),
                            onTertiary = Color(0xFF113447),
                            tertiaryContainer = Color(0xFF2B4A5F),
                            onTertiaryContainer = Color(0xFFC8E6FF),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF191C1B),
                            onBackground = Color(0xFFE1E3E0),
                            surface = Color(0xFF191C1B),
                            onSurface = Color(0xFFE1E3E0),
                            surfaceVariant = Color(0xFF3F4945),
                            onSurfaceVariant = Color(0xFFBEC9C4),
                            outline = Color(0xFF89938F),
                            outlineVariant = Color(0xFF3F4945),
                    )
    ),

    /** 蓝色 */
    BLUE(
            key = "blue",
            seedColor = Color(0xFF1565C0),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF1565C0),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFD4E3FF),
                            onPrimaryContainer = Color(0xFF001C3A),
                            secondary = Color(0xFF555F71),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFD9E3F8),
                            onSecondaryContainer = Color(0xFF121C2B),
                            tertiary = Color(0xFF6E5676),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFF8D8FE),
                            onTertiaryContainer = Color(0xFF271430),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFDFBFF),
                            onBackground = Color(0xFF1B1B1F),
                            surface = Color(0xFFFDFBFF),
                            onSurface = Color(0xFF1B1B1F),
                            surfaceVariant = Color(0xFFE0E2EC),
                            onSurfaceVariant = Color(0xFF44474E),
                            outline = Color(0xFF74777F),
                            outlineVariant = Color(0xFFC4C6CF),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFA5C8FF),
                            onPrimary = Color(0xFF00325E),
                            primaryContainer = Color(0xFF004A85),
                            onPrimaryContainer = Color(0xFFD4E3FF),
                            secondary = Color(0xFFBDC7DB),
                            onSecondary = Color(0xFF273141),
                            secondaryContainer = Color(0xFF3E4758),
                            onSecondaryContainer = Color(0xFFD9E3F8),
                            tertiary = Color(0xFFDBBCE2),
                            onTertiary = Color(0xFF3D2846),
                            tertiaryContainer = Color(0xFF553F5D),
                            onTertiaryContainer = Color(0xFFF8D8FE),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1B1B1F),
                            onBackground = Color(0xFFE4E2E6),
                            surface = Color(0xFF1B1B1F),
                            onSurface = Color(0xFFE4E2E6),
                            surfaceVariant = Color(0xFF44474E),
                            onSurfaceVariant = Color(0xFFC4C6CF),
                            outline = Color(0xFF8E9099),
                            outlineVariant = Color(0xFF44474E),
                    )
    ),

    /** 紫色 */
    PURPLE(
            key = "purple",
            seedColor = Color(0xFF7B1FA2),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF7B1FA2),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFF1DAFF),
                            onPrimaryContainer = Color(0xFF2C004E),
                            secondary = Color(0xFF665A6F),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFEDDEF7),
                            onSecondaryContainer = Color(0xFF21182A),
                            tertiary = Color(0xFF805159),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFFFD9DE),
                            onTertiaryContainer = Color(0xFF321018),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF1E1A20),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF1E1A20),
                            surfaceVariant = Color(0xFFE9DFEA),
                            onSurfaceVariant = Color(0xFF4B454D),
                            outline = Color(0xFF7C757E),
                            outlineVariant = Color(0xFFCCC4CE),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFDEB7FF),
                            onPrimary = Color(0xFF49007A),
                            primaryContainer = Color(0xFF620089),
                            onPrimaryContainer = Color(0xFFF1DAFF),
                            secondary = Color(0xFFD1C2DB),
                            onSecondary = Color(0xFF362D40),
                            secondaryContainer = Color(0xFF4D4357),
                            onSecondaryContainer = Color(0xFFEDDEF7),
                            tertiary = Color(0xFFF3B7BF),
                            onTertiary = Color(0xFF4B252C),
                            tertiaryContainer = Color(0xFF653A42),
                            onTertiaryContainer = Color(0xFFFFD9DE),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1E1A20),
                            onBackground = Color(0xFFE8E0E5),
                            surface = Color(0xFF1E1A20),
                            onSurface = Color(0xFFE8E0E5),
                            surfaceVariant = Color(0xFF4B454D),
                            onSurfaceVariant = Color(0xFFCCC4CE),
                            outline = Color(0xFF968E98),
                            outlineVariant = Color(0xFF4B454D),
                    )
    ),

    /** 粉色 */
    PINK(
            key = "pink",
            seedColor = Color(0xFFC2185B),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFFC2185B),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFFD9E1),
                            onPrimaryContainer = Color(0xFF3F001B),
                            secondary = Color(0xFF75565D),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFFFD9E1),
                            onSecondaryContainer = Color(0xFF2B151B),
                            tertiary = Color(0xFF7C5635),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFFFDCC3),
                            onTertiaryContainer = Color(0xFF2E1500),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF201A1C),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF201A1C),
                            surfaceVariant = Color(0xFFF3DDE1),
                            onSurfaceVariant = Color(0xFF514347),
                            outline = Color(0xFF847377),
                            outlineVariant = Color(0xFFD6C2C5),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFFFB1C4),
                            onPrimary = Color(0xFF650030),
                            primaryContainer = Color(0xFF8E0044),
                            onPrimaryContainer = Color(0xFFFFD9E1),
                            secondary = Color(0xFFE4BDC5),
                            onSecondary = Color(0xFF43292F),
                            secondaryContainer = Color(0xFF5B3F46),
                            onSecondaryContainer = Color(0xFFFFD9E1),
                            tertiary = Color(0xFFEFBD94),
                            onTertiary = Color(0xFF48290B),
                            tertiaryContainer = Color(0xFF623F1F),
                            onTertiaryContainer = Color(0xFFFFDCC3),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF201A1C),
                            onBackground = Color(0xFFEBE0E1),
                            surface = Color(0xFF201A1C),
                            onSurface = Color(0xFFEBE0E1),
                            surfaceVariant = Color(0xFF514347),
                            onSurfaceVariant = Color(0xFFD6C2C5),
                            outline = Color(0xFF9E8C90),
                            outlineVariant = Color(0xFF514347),
                    )
    ),

    /** 橙色 */
    ORANGE(
            key = "orange",
            seedColor = Color(0xFFE65100),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFFBF360C),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFFFDBCF),
                            onPrimaryContainer = Color(0xFF3A0B00),
                            secondary = Color(0xFF77574C),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFFFDBCF),
                            onSecondaryContainer = Color(0xFF2C160D),
                            tertiary = Color(0xFF6B5E2F),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFF4E2A7),
                            onTertiaryContainer = Color(0xFF231B00),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFFFBFF),
                            onBackground = Color(0xFF201A17),
                            surface = Color(0xFFFFFBFF),
                            onSurface = Color(0xFF201A17),
                            surfaceVariant = Color(0xFFF5DED5),
                            onSurfaceVariant = Color(0xFF53443D),
                            outline = Color(0xFF85746C),
                            outlineVariant = Color(0xFFD8C2B8),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFFFFB59C),
                            onPrimary = Color(0xFF5F1600),
                            primaryContainer = Color(0xFF862200),
                            onPrimaryContainer = Color(0xFFFFDBCF),
                            secondary = Color(0xFFE7BEAF),
                            onSecondary = Color(0xFF442A21),
                            secondaryContainer = Color(0xFF5D4036),
                            onSecondaryContainer = Color(0xFFFFDBCF),
                            tertiary = Color(0xFFD7C68D),
                            onTertiary = Color(0xFF3A3005),
                            tertiaryContainer = Color(0xFF52461A),
                            onTertiaryContainer = Color(0xFFF4E2A7),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF201A17),
                            onBackground = Color(0xFFEDE0DB),
                            surface = Color(0xFF201A17),
                            onSurface = Color(0xFFEDE0DB),
                            surfaceVariant = Color(0xFF53443D),
                            onSurfaceVariant = Color(0xFFD8C2B8),
                            outline = Color(0xFFA08D84),
                            outlineVariant = Color(0xFF53443D),
                    )
    ),

    /** 绿色 */
    GREEN(
            key = "green",
            seedColor = Color(0xFF2E7D32),
            lightScheme =
                    lightColorScheme(
                            primary = Color(0xFF2E7D32),
                            onPrimary = Color(0xFFFFFFFF),
                            primaryContainer = Color(0xFFA8F5AB),
                            onPrimaryContainer = Color(0xFF002106),
                            secondary = Color(0xFF52634F),
                            onSecondary = Color(0xFFFFFFFF),
                            secondaryContainer = Color(0xFFD5E8CF),
                            onSecondaryContainer = Color(0xFF101F10),
                            tertiary = Color(0xFF38656A),
                            onTertiary = Color(0xFFFFFFFF),
                            tertiaryContainer = Color(0xFFBCEBF1),
                            onTertiaryContainer = Color(0xFF002023),
                            error = Color(0xFFBA1A1A),
                            onError = Color(0xFFFFFFFF),
                            errorContainer = Color(0xFFFFDAD6),
                            onErrorContainer = Color(0xFF410002),
                            background = Color(0xFFFCFDF7),
                            onBackground = Color(0xFF1A1C19),
                            surface = Color(0xFFFCFDF7),
                            onSurface = Color(0xFF1A1C19),
                            surfaceVariant = Color(0xFFDEE5D9),
                            onSurfaceVariant = Color(0xFF424940),
                            outline = Color(0xFF72796F),
                            outlineVariant = Color(0xFFC2C9BD),
                    ),
            darkScheme =
                    darkColorScheme(
                            primary = Color(0xFF8CD891),
                            onPrimary = Color(0xFF003910),
                            primaryContainer = Color(0xFF0E5319),
                            onPrimaryContainer = Color(0xFFA8F5AB),
                            secondary = Color(0xFFB9CCB3),
                            onSecondary = Color(0xFF253424),
                            secondaryContainer = Color(0xFF3B4B39),
                            onSecondaryContainer = Color(0xFFD5E8CF),
                            tertiary = Color(0xFFA0CFD4),
                            onTertiary = Color(0xFF00373B),
                            tertiaryContainer = Color(0xFF1F4D52),
                            onTertiaryContainer = Color(0xFFBCEBF1),
                            error = Color(0xFFFFB4AB),
                            onError = Color(0xFF690005),
                            errorContainer = Color(0xFF93000A),
                            onErrorContainer = Color(0xFFFFDAD6),
                            background = Color(0xFF1A1C19),
                            onBackground = Color(0xFFE2E3DD),
                            surface = Color(0xFF1A1C19),
                            onSurface = Color(0xFFE2E3DD),
                            surfaceVariant = Color(0xFF424940),
                            onSurfaceVariant = Color(0xFFC2C9BD),
                            outline = Color(0xFF8C9388),
                            outlineVariant = Color(0xFF424940),
                    )
    );

    companion object {
        /** 根据 key 字符串获取对应枚举，找不到则返回 DYNAMIC */
        fun fromKey(key: String): ThemeColor = entries.find { it.key == key } ?: DYNAMIC
    }
}
